-- =========================================================
-- SMART RESTAURANT MANAGEMENT SYSTEM DATABASE
-- PostgreSQL / Supabase Compatible (Fully Corrected)
-- =========================================================

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS tables CASCADE;

-- =========================================================
-- 1. TABLES CREATION
-- =========================================================

CREATE TABLE IF NOT EXISTS tables (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number INT NOT NULL UNIQUE,
    capacity INT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('available','occupied','reserved'))
);

CREATE TABLE IF NOT EXISTS menu_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Starters','Main Course','Beverages','Desserts')),
    price NUMERIC(10,2) NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    prep_time_mins INT NOT NULL,
    dietary_type TEXT NOT NULL CHECK (dietary_type IN ('Veg','Non-Veg','Jain')),
    image_url TEXT,
    model_3d_url TEXT
);

CREATE TABLE IF NOT EXISTS inventory (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    current_stock NUMERIC(10,2),
    unit TEXT NOT NULL CHECK (unit IN ('kg','liters','packets')),
    reorder_level NUMERIC(10,2),
    cost_per_unit NUMERIC(10,2)
);

CREATE TABLE IF NOT EXISTS staff (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Manager','Head Chef','Waiter')),
    shift_status TEXT NOT NULL CHECK (shift_status IN ('On Duty','Off Duty'))
);

CREATE TABLE IF NOT EXISTS orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id INT REFERENCES tables(id) ON DELETE CASCADE,
    customer_name TEXT,
    customer_phone TEXT,
    total_amount NUMERIC(10,2),
    status TEXT NOT NULL CHECK (status IN ('pending','preparing','ready','served','completed')),
    payment_status TEXT NOT NULL CHECK (payment_status IN ('unpaid','paid')),
    payment_method TEXT NOT NULL CHECK (payment_method IN ('UPI','Cash','Card')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id INT REFERENCES menu_items(id),
    quantity INT NOT NULL,
    price_at_time NUMERIC(10,2)
);

-- =========================================================
-- 2. TABLE DATA INSERTIONS
-- =========================================================

-- TABLES (10)
INSERT INTO tables (id, table_number, capacity, status) VALUES
(1,1,2,'available'),
(2,2,2,'occupied'),
(3,3,4,'reserved'),
(4,4,4,'occupied'),
(5,5,6,'available'),
(6,6,2,'occupied'),
(7,7,8,'available'),
(8,8,4,'reserved'),
(9,9,6,'occupied'),
(10,10,2,'available');

-- MENU ITEMS (15)
INSERT INTO menu_items (id, name, category, price, is_available, prep_time_mins, dietary_type, image_url, model_3d_url) VALUES
(1,'Paneer Tikka','Starters',299,TRUE,15,'Veg','https://picsum.photos/400?1','https://modelviewer.dev/shared-assets/models/Astronaut.glb'),
(2,'Chicken Tikka','Starters',349,TRUE,18,'Non-Veg','https://picsum.photos/400?2','https://modelviewer.dev/shared-assets/models/Astronaut.glb'),
(3,'Veg Spring Rolls','Starters',229,TRUE,12,'Veg','https://picsum.photos/400?3',NULL),
(4,'Butter Chicken','Main Course',499,TRUE,22,'Non-Veg','https://picsum.photos/400?4','https://modelviewer.dev/shared-assets/models/Astronaut.glb'),
(5,'Paneer Butter Masala','Main Course',379,TRUE,20,'Veg','https://picsum.photos/400?5',NULL),
(6,'Dal Makhani','Main Course',289,TRUE,18,'Veg','https://picsum.photos/400?6',NULL),
(7,'Jain Veg Curry','Main Course',329,TRUE,18,'Jain','https://picsum.photos/400?7',NULL),
(8,'Veg Biryani','Main Course',349,TRUE,20,'Veg','https://picsum.photos/400?8',NULL),
(9,'Chicken Biryani','Main Course',449,TRUE,25,'Non-Veg','https://picsum.photos/400?9','https://modelviewer.dev/shared-assets/models/Astronaut.glb'),
(10,'Masala Chai','Beverages',80,TRUE,5,'Veg','https://picsum.photos/400?10',NULL),
(11,'Cold Coffee','Beverages',180,TRUE,6,'Veg','https://picsum.photos/400?11',NULL),
(12,'Fresh Lime Soda','Beverages',120,FALSE,4,'Veg','https://picsum.photos/400?12',NULL),
(13,'Gulab Jamun','Desserts',140,TRUE,5,'Veg','https://picsum.photos/400?13',NULL),
(14,'Chocolate Brownie','Desserts',220,TRUE,8,'Veg','https://picsum.photos/400?14',NULL),
(15,'Rasmalai','Desserts',180,TRUE,6,'Veg','https://picsum.photos/400?15',NULL);

-- INVENTORY (10)
INSERT INTO inventory (id, item_name, current_stock, unit, reorder_level, cost_per_unit) VALUES
(1,'Paneer',25,'kg',10,320),
(2,'Milk',50,'liters',15,65),
(3,'Rice',100,'kg',30,72),
(4,'Chicken',45,'kg',20,280),
(5,'Butter',20,'kg',8,520),
(6,'Flour',80,'kg',25,42),
(7,'Cooking Oil',40,'liters',15,160),
(8,'Soft Drink Bottles',60,'packets',20,420),
(9,'Tea Leaves',15,'kg',5,480),
(10,'Sugar',55,'kg',20,45);

-- STAFF (5)
INSERT INTO staff (id, name, role, shift_status) VALUES
(1,'Rahul Sharma','Manager','On Duty'),
(2,'Amit Verma','Head Chef','On Duty'),
(3,'Sandeep Singh','Waiter','On Duty'),
(4,'Priya Kapoor','Waiter','Off Duty'),
(5,'Neha Arora','Waiter','On Duty');

-- ORDERS (30)
INSERT INTO orders (id, table_id, customer_name, customer_phone, total_amount, status, payment_status, payment_method, created_at) VALUES
(1,2,'Aarav','9876500001',599,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '30 days'),
(2,4,'Vihaan','9876500002',420,'completed','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '29 days'),
(3,6,'Anaya','9876500003',890,'served','paid','Card',CURRENT_TIMESTAMP-INTERVAL '28 days'),
(4,9,'Kabir','9876500004',650,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '27 days'),
(5,2,'Ishita','9876500005',980,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '26 days'),
(6,5,'Reyansh','9876500006',740,'served','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '25 days'),
(7,7,'Diya','9876500007',355,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '24 days'),
(8,1,'Aditya','9876500008',690,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '23 days'),
(9,3,'Sara','9876500009',250,'completed','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '22 days'),
(10,4,'Arjun','9876500010',810,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '21 days'),
(11,5,'Riya','9876500011',445,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '20 days'),
(12,6,'Karan','9876500012',520,'served','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '19 days'),
(13,7,'Naina','9876500013',610,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '18 days'),
(14,8,'Rohan','9876500014',920,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '17 days'),
(15,9,'Siya','9876500015',310,'completed','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '16 days'),
(16,10,'Aryan','9876500016',790,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '15 days'),
(17,1,'Aisha','9876500017',650,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '14 days'),
(18,2,'Dev','9876500018',470,'served','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '13 days'),
(19,3,'Meera','9876500019',530,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '12 days'),
(20,4,'Vivaan','9876500020',880,'completed','paid','Card',CURRENT_TIMESTAMP-INTERVAL '11 days'),
(21,5,'Tara','9876500021',345,'completed','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '10 days'),
(22,6,'Laksh','9876500022',765,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '9 days'),
(23,7,'Myra','9876500023',510,'served','paid','Card',CURRENT_TIMESTAMP-INTERVAL '8 days'),
(24,8,'Krish','9876500024',690,'completed','paid','Cash',CURRENT_TIMESTAMP-INTERVAL '7 days'),
(25,9,'Pari','9876500025',430,'completed','paid','UPI',CURRENT_TIMESTAMP-INTERVAL '6 days'),
(26,10,'Yash','9876500026',620,'ready','unpaid','Cash',CURRENT_TIMESTAMP-INTERVAL '5 days'),
(27,2,'Anvi','9876500027',780,'preparing','unpaid','UPI',CURRENT_TIMESTAMP-INTERVAL '4 days'),
(28,4,'Harsh','9876500028',550,'pending','unpaid','Card',CURRENT_TIMESTAMP-INTERVAL '3 days'),
(29,6,'Rudra','9876500029',970,'preparing','unpaid','UPI',CURRENT_TIMESTAMP-INTERVAL '2 days'),
(30,9,'Kiara','9876500030',460,'pending','unpaid','Cash',CURRENT_TIMESTAMP-INTERVAL '1 day');

-- ORDER ITEMS (60)
INSERT INTO order_items (id, order_id, menu_item_id, quantity, price_at_time) VALUES
(1,1,4,1,499),(2,1,10,1,80),
(3,2,5,1,379),(4,2,13,1,140),
(5,3,9,2,449),(6,3,11,1,180),
(7,4,4,1,499),(8,4,15,1,180),
(9,5,2,2,349),(10,5,10,2,80),
(11,6,8,2,349),(12,6,13,1,140),
(13,7,1,1,299),(14,7,11,1,180),
(15,8,9,1,449),(16,8,14,1,220),
(17,9,3,1,229),(18,9,10,1,80),
(19,10,4,1,499),(20,10,13,2,140),
(21,11,5,1,379),(22,11,12,1,120),
(23,12,8,1,349),(24,12,15,1,180),
(25,13,1,2,299),(26,13,10,1,80),
(27,14,9,2,449),(28,14,14,1,220),
(29,15,6,1,289),(30,15,13,1,140),
(31,16,4,1,499),(32,16,11,1,180),
(33,17,5,1,379),(34,17,15,1,180),
(35,18,8,1,349),(36,18,10,1,80),
(37,19,7,1,329),(38,19,13,1,140),
(39,20,2,2,349),(40,20,14,1,220),
(41,21,1,1,299),(42,21,11,1,180),
(43,22,9,1,449),(44,22,15,1,180),
(45,23,6,1,289),(46,23,10,1,80),
(47,24,5,1,379),(48,24,13,1,140),
(49,25,8,1,349),(50,25,11,1,180),
(51,26,4,1,499),(52,26,14,1,220),
(53,27,9,2,449),(54,27,10,1,80),
(55,28,5,1,379),(56,28,13,1,140),
(57,29,2,2,349),(58,29,15,1,180),
(59,30,1,1,299),(60,30,11,1,180);

-- =========================================================
-- 3. SEQUENCE RESET FOR AUTO-INCREMENT NEW ORDERS
-- =========================================================

SELECT setval(pg_get_serial_sequence('tables', 'id'), (SELECT MAX(id) FROM tables));
SELECT setval(pg_get_serial_sequence('menu_items', 'id'), (SELECT MAX(id) FROM menu_items));
SELECT setval(pg_get_serial_sequence('inventory', 'id'), (SELECT MAX(id) FROM inventory));
SELECT setval(pg_get_serial_sequence('staff', 'id'), (SELECT MAX(id) FROM staff));
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT MAX(id) FROM orders));
SELECT setval(pg_get_serial_sequence('order_items', 'id'), (SELECT MAX(id) FROM order_items));



-- ==========================================
-- SERVICE REQUESTS TABLE
-- ==========================================

DROP TABLE IF EXISTS service_requests CASCADE;

CREATE TABLE service_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    table_no TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    service TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    accepted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

-- ==========================================
-- ENABLE RLS
-- ==========================================

ALTER TABLE service_requests
ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- POLICIES
-- ==========================================

CREATE POLICY "Anyone can insert requests"
ON service_requests
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Anyone can read requests"
ON service_requests
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Anyone can update requests"
ON service_requests
FOR UPDATE
TO anon, authenticated
USING (true);

CREATE POLICY "Anyone can delete requests"
ON service_requests
FOR DELETE
TO anon, authenticated
USING (true);

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX idx_service_status
ON service_requests(status);

CREATE INDEX idx_service_created
ON service_requests(created_at);

-- ==========================================
-- SAMPLE DATA
-- ==========================================

INSERT INTO service_requests
(table_no, customer_name, service)
VALUES
('5', 'Rahul', '💧 Extra Water'),
('3', 'Priya', '🧾 Bring Bill'),
('8', 'Aman', '🥤 Drink Refill');ml;l[kpo-0  op[]]